# Generated by Django 4.1.3 on 2023-01-06 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='titulo_tag',
            field=models.CharField(default='Mi_Blog', max_length=255),
        ),
    ]
