# Generated by Django 4.1.3 on 2023-01-08 21:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('miblog', '0004_categoria_post_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='megusta',
            field=models.ManyToManyField(related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
