# Generated by Django 4.1.3 on 2023-01-10 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miblog', '0007_post_resumen'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imgenc',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/'),
        ),
    ]
