# Generated by Django 4.1.3 on 2023-01-10 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miblog', '0009_alter_post_imgenc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='imgenc',
        ),
    ]
